import { ExamData } from 'isncsci-ui/dist/esm/core/domain';

export const inputFieldNames: Array<keyof ExamData> = [
    // Right Light Touch
    'rightLightTouchC2',
    'rightLightTouchC3',
    'rightLightTouchC4',
    'rightLightTouchC5',
    'rightLightTouchC6',
    'rightLightTouchC7',
    'rightLightTouchC8',
    'rightLightTouchT1',
    'rightLightTouchT2',
    'rightLightTouchT3',
    'rightLightTouchT4',
    'rightLightTouchT5',
    'rightLightTouchT6',
    'rightLightTouchT7',
    'rightLightTouchT8',
    'rightLightTouchT9',
    'rightLightTouchT10',
    'rightLightTouchT11',
    'rightLightTouchT12',
    'rightLightTouchL1',
    'rightLightTouchL2',
    'rightLightTouchL3',
    'rightLightTouchL4',
    'rightLightTouchL5',
    'rightLightTouchS1',
    'rightLightTouchS2',
    'rightLightTouchS3',
    'rightLightTouchS4_5',

    // Right Pin Prick
    'rightPinPrickC2',
    'rightPinPrickC3',
    'rightPinPrickC4',
    'rightPinPrickC5',
    'rightPinPrickC6',
    'rightPinPrickC7',
    'rightPinPrickC8',
    'rightPinPrickT1',
    'rightPinPrickT2',
    'rightPinPrickT3',
    'rightPinPrickT4',
    'rightPinPrickT5',
    'rightPinPrickT6',
    'rightPinPrickT7',
    'rightPinPrickT8',
    'rightPinPrickT9',
    'rightPinPrickT10',
    'rightPinPrickT11',
    'rightPinPrickT12',
    'rightPinPrickL1',
    'rightPinPrickL2',
    'rightPinPrickL3',
    'rightPinPrickL4',
    'rightPinPrickL5',
    'rightPinPrickS1',
    'rightPinPrickS2',
    'rightPinPrickS3',
    'rightPinPrickS4_5',

    // Left Light Touch
    'leftLightTouchC2',
    'leftLightTouchC3',
    'leftLightTouchC4',
    'leftLightTouchC5',
    'leftLightTouchC6',
    'leftLightTouchC7',
    'leftLightTouchC8',
    'leftLightTouchT1',
    'leftLightTouchT2',
    'leftLightTouchT3',
    'leftLightTouchT4',
    'leftLightTouchT5',
    'leftLightTouchT6',
    'leftLightTouchT7',
    'leftLightTouchT8',
    'leftLightTouchT9',
    'leftLightTouchT10',
    'leftLightTouchT11',
    'leftLightTouchT12',
    'leftLightTouchL1',
    'leftLightTouchL2',
    'leftLightTouchL3',
    'leftLightTouchL4',
    'leftLightTouchL5',
    'leftLightTouchS1',
    'leftLightTouchS2',
    'leftLightTouchS3',
    'leftLightTouchS4_5',

    // Left Pin Prick
    'leftPinPrickC2',
    'leftPinPrickC3',
    'leftPinPrickC4',
    'leftPinPrickC5',
    'leftPinPrickC6',
    'leftPinPrickC7',
    'leftPinPrickC8',
    'leftPinPrickT1',
    'leftPinPrickT2',
    'leftPinPrickT3',
    'leftPinPrickT4',
    'leftPinPrickT5',
    'leftPinPrickT6',
    'leftPinPrickT7',
    'leftPinPrickT8',
    'leftPinPrickT9',
    'leftPinPrickT10',
    'leftPinPrickT11',
    'leftPinPrickT12',
    'leftPinPrickL1',
    'leftPinPrickL2',
    'leftPinPrickL3',
    'leftPinPrickL4',
    'leftPinPrickL5',
    'leftPinPrickS1',
    'leftPinPrickS2',
    'leftPinPrickS3',
    'leftPinPrickS4_5',

    // Right Motor
    'rightMotorC5',
    'rightMotorC6',
    'rightMotorC7',
    'rightMotorC8',
    'rightMotorT1',
    'rightMotorL2',
    'rightMotorL3',
    'rightMotorL4',
    'rightMotorL5',
    'rightMotorS1',

    // Left Motor
    'leftMotorC5',
    'leftMotorC6',
    'leftMotorC7',
    'leftMotorC8',
    'leftMotorT1',
    'leftMotorL2',
    'leftMotorL3',
    'leftMotorL4',
    'leftMotorL5',
    'leftMotorS1',

    // Additional Fields
    'voluntaryAnalContraction',
    'deepAnalPressure',
    'rightLowestNonKeyMuscleWithMotorFunction',
    'leftLowestNonKeyMuscleWithMotorFunction',
    'comments',
];
